server:
  port: 8082

spring:
  application:
    name: receive-server
  cloud:
   stream:
     bindings: #多个通道
      firstMe:  # 这个名字是一个通道的名称
        destination: firstMeExchange # 表示要使用的Exchange名称定义
        context-type: text/plain # 设置消息类型，本次为对象json   application/json ，如果是文本则设置“text/plain”
        group: addProductHandler      # 拥有 group 默认会持久化队列

  rabbitmq:
    host: 112.74.43.136
    port: 5672
    username: cat
    password: cat

